### ISSUE TITLE
Can't copy stages within the editor

### ISSUE THREAD

**Issue by RhapsodySL** [Tempus/Basement-Renovator#1]
You can't copy individual stages within the editor if you want to move a stage over to another floor (say, if I wanted to copy one of my custom Basement stages to the Cellar). I would appreciate if it would be possible to do many stages at once, since I plan to make a mod that contains a ton of new stages, but I don't want to have to manually redo each stage for a floor's variant.

**Comment by Tempus** [comment]
This was fixed a while ago, but never closed.
