### ISSUE TITLE
Frequent crashes when using Entity Stacking feature

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#105]
Need to code this differently to avoid the crash?

**Comment by Zamiell** [comment]
Apparently this only happens on Windows and not MacOS, and has to do with the library that Chrono used to code it.

**Comment by budjmt** [comment]
Can you provide a little more information?

**Comment by budjmt** [comment]
What's tipped you off it was the library? (which library btw) When in the stacking process does the crash happen?

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/129 fixed here, but that has indentation issues so the followup fix is also needed

**Comment by Zamiell** [comment]
closing this then

**Comment by budjmt** [comment]
follow up: https://github.com/Tempus/Basement-Renovator/pull/131
