### ISSUE TITLE
Basement Renovator changes every entity weight 1 to weight 2 when saving a STB

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#11]
Steps to reproduce:
1) Unpack the XML from a fresh 01.basement.stb file using Rick's unpacker
2) Use Basement Renovator to open 01.basement.stb, save as 01.basement2.stb
3) Unpack the XML from 01.basement2.stb using Rick's unpacker
4) Compare the 2 XML files

**Comment by Tempus** [comment]
Fixed.
