### ISSUE TITLE
Trinket "Filigree Feather" spawns as "Hairpin"

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#113]
If you try to place the "Filigree Feather" Trinket, it spawns as "Hairpin" Trinket.
The subtype is set to 120, but it should be 123.

Here is the fixed line of code (Line 1211 in entitiesAfterbirthPlus.xml):
`<entity Group="Trinkets" ID="5" Image="resources/Entities/Trinkets/5.350.123 - Filigree Feather.png" Kind="Collect" Name="Filigree Feather" Subtype="123" Variant="350" />`

**Comment by Tempus** [comment]
https://github.com/Tempus/Basement-Renovator/commit/a810e5949ae1cc18a31423964bef772d5af41c65
