### ISSUE TITLE
Log Error I get when trying to run Basement Renovator

### ISSUE THREAD

**Issue by vapingdolphin** [Tempus/Basement-Renovator#114]
When I try to run the program, I'm presented with a log with this error..

" Traceback (most recent call last):
  File "BasementRenovatorAfterbirth.py", line 34, in <module>
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 109, in load_module
ImportError: MemoryLoadLibrary failed loading PyQt5\QtCore.pyd: The specified module could not be found. (126) "

**Comment by Zamiell** [comment]
Closed due to this guy not responding.
