### ISSUE TITLE
Entity Identification

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#12]
"Ladders or something? 0.30.0 = grass

"Ladders or something? 0.10.0 = grass

Screenshot: http://i.imgur.com/7Nu0nN7.png

**Comment by Zamiell** [comment]
Actually I guess its a random thing that changes?

**Comment by Tempus** [comment]
Yeah, I it's 'deco', so I should probably update that.

**Comment by Tempus** [comment]
Added.
