### ISSUE TITLE
Add Lucky Penny & Sticky Nickel Pickup

### ISSUE THREAD

**Issue by sillypears** [Tempus/Basement-Renovator#13]
The lucky penny pickup & sticky nickel are visually the same as a normal images. The lucky penny id is 5.20.5 and the sticky nickel id is 5.20.6, I made some mockups of the potential images.

![5 20 5 - lucky penny](https://cloud.githubusercontent.com/assets/13240985/12071892/4a37fb94-b092-11e5-9615-eb9e7d3d3eff.png)
![5 20 6 - sticky nickel](https://cloud.githubusercontent.com/assets/13240985/12071899/9dcc08c2-b092-11e5-83a2-deb912c827bc.png)

**Comment by Tempus** [comment]
Done! Took graphics from the game in the end.

**Comment by sillypears** [comment]
There are no graphics in the game for the 2 items. They appear identical to the normal ones.
