### ISSUE TITLE
Tiles anchored incorrectly in non-standard room sizes

### ISSUE THREAD

**Issue by TaigaTreant** [Tempus/Basement-Renovator#148]
Rooms with non-standard sizes (such as thin rooms and closets) have their valid tiles anchored to the top-left of their corresponding standard size rooms as opposed to the correct top-left of the non-standard size room. As a result objects can be placed out-of-bounds in these rooms, while placing objects in-bounds requires first placing an object out-of-bounds then dragging in-bounds. Below is an in-editor example of rocks filling all tiles currently set as valid for a closet room.

![out-of-bounds rocks example](https://user-images.githubusercontent.com/23194420/51555541-cf3d7980-1e45-11e9-9669-a8cd1fab3c18.png)

**Comment by Zamiell** [comment]
bud says that he will most likely handle this in conjunction with #46 . Exciting stuff.

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/180

**Comment by Zamiell** [comment]
fixed!
