### ISSUE TITLE
Missing door entries should default to non-existing

### ISSUE THREAD

**Issue by budjmt** [Tempus/Basement-Renovator#154]
There are a few rooms in the game that are missing door entries, e.g. Sac Room 5, Devil Room 14, Angel Room 6, Barren Room 14. In editor, these doors are not spawned. However, these missing door rooms don't crash in game, instead they are just treated as non-existent. These doors should be displayed in BR anyway, and there should be a log statement indicating missing doors.

**Comment by budjmt** [comment]
Touched base with Zamiel, apparently this leads to legitimate issues where for the deal rooms when attempting to enter from an invalid door slot you get warped to one of the doors at random. This means we probably don't need to support the feature per se, but we should be logging those rooms.

**Comment by Zamiell** [comment]
also i believe you missed some boss rooms that are missing doors. i don't remember which exactly but i remember at least gate from this list. maybe others:

https://github.com/Zamiell/isaac-racing-client/blob/master/mod/CHANGES-ROOM.md#boss-room-door-fix-part-2

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/156 addressed in the capacity I think is reasonable here. BR is technically correct to display them in this way, and it can and should be fixed on a case by case basis in the xml directly in rep. I'm not even sure how this happened in the first place.
