### ISSUE TITLE
Able to add items out of bounds

### ISSUE THREAD

**Issue by sillypears** [Tempus/Basement-Renovator#16]
If you click to add anything at the edge of a room, and then drag outwards, it appears you can put the items out of bounds. See image below.

![image](https://cloud.githubusercontent.com/assets/13240985/12071988/681cab00-b097-11e5-887b-a0774003a406.png)

**Comment by Tempus** [comment]
Pushed a fix, hopefully that'll do it.

**Comment by Tempus** [comment]
Confirmed fixed
