### ISSUE TITLE
The "dirty" flag gets set when testing a room

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#163]
Testing a room doesn't actually change the room, so the BR icon should not change to red.

**Comment by Zamiell** [comment]
```
budjmt Today at 12:13 PM
There's actually some logic to this iirc
I'll double check later but I remember thinking that was weird too and then saw the basic rationale. Might not be worth the confusion though
```

**Comment by Zamiell** [comment]
@budjmt So what was the logic?

**Comment by budjmt** [comment]
I'm going to assume the original logic was left over from when the tests replaced game files you could be editing and wasn't restoring them afterwards or something. It's probably irrelevant now looking at what the current code does.

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/167

**Comment by Zamiell** [comment]
nice thank you
