### ISSUE TITLE
Make BR accept an argument for file to open so it can be associated with stbs

### ISSUE THREAD

**Issue by budjmt** [Tempus/Basement-Renovator#168]
Would be very nice to have

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/169

**Comment by budjmt** [comment]
the association will only work in the built version, windows is silly

**Comment by Zamiell** [comment]
that's a shame. have you tested it on the built version?

**Comment by budjmt** [comment]
what I mean is that windows will not let you associate non-executable file types, even if you can normally run them via double click
