### ISSUE TITLE
Exporting rooms reorganises last room in list to the top of the list.

### ISSUE THREAD

**Issue by Erfly** [Tempus/Basement-Renovator#175]
Essentially, when a list of rooms is exported, the final room in the list will typically then be on the top of the list of rooms in the file they're exported to. 
(A, B, C, D) exported to (E, F) becomes (E, F, D, A, B, C)

**Comment by budjmt** [comment]
ugh this is because of how Qt selections work. Basically they'll be arranged in the order you added them to your selection and not reflect their order in the list. I'll think about how I want to approach this fix.

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/177

**Comment by Zamiell** [comment]
should be fixed now, reopen if not
