### ISSUE TITLE
Mouseover tooltip often seems to get stuck.

### ISSUE THREAD

**Issue by Erfly** [Tempus/Basement-Renovator#176]
Very minor issue, but the tooltip will remain in place over a previous location if the new tooltip would be the same.

This occurs for entities with the same names, or rooms with the same ID/sub and settings.

**Comment by budjmt** [comment]
I've done some googling and can't find any information on this behavior. I also don't see anything particularly unusual about how this is coded, so I'm going to assume it's either an underdocumented windows and qt feature. Working around this would probably be a pain, so I'm calling this a won't fix
