### ISSUE TITLE
Improvement ideas for BR "Replace Stage" feature

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#184]
Often times when I am testing rooms, I enable all of the doors if they are not already enabled. That way they will fill the entire floor. I think this is what BR should do, even though it seems weird.

When the user pressed the OK button, it would reset the doors back to the way it was before.

**Comment by budjmt** [comment]
Other ideas: Dad's Key and debug 8 on start

**Comment by budjmt** [comment]
It could be interesting if you could select multiple rooms to test for stage mode, also reseed the floor until at least one instance of your room(s) shows up.

**Comment by Zamiell** [comment]
oh that is a really good idea too

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/185 I have some other ideas for multi-room which I'll do later

**Comment by budjmt** [comment]
Multiroom testing, requires newest stageapi: https://github.com/Tempus/Basement-Renovator/commit/746114652d79d8ba54f8af10727e443b2855f3fd

**Comment by Zamiell** [comment]
very nice!
