### ISSUE TITLE
new HUD thing is near-impossible to read on Windows 7

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#19]
Here's what it looks like for me, why is it so tiny?

http://i.imgur.com/KbCiRG1.png

**Comment by sillypears** [comment]
2nd row is a bit harder to read on Win10 as well

![image](https://cloud.githubusercontent.com/assets/13240985/12072105/9574ec46-b09e-11e5-9b5d-e3fd20fb2cd9.png)

**Comment by Tempus** [comment]
Increased font sizes from 8 and 12 to 10 and 13. Is that enough?

**Comment by Zamiell** [comment]
Fine for now I guess.

**Comment by Zamiell** [comment]
In the latest commit this bug is back - not sure what changed but its back to being super tiny.

**Comment by Zamiell** [comment]
Never mind, my GitHub client apparently downloaded an older version or something.
