### ISSUE TITLE
No resources folder?

### ISSUE THREAD

**Issue by BenjaminD06** [Tempus/Basement-Renovator#190]
Well, I'm trying to run the Basement Renovator and it give me this error:
'No such file or directory 'resources/EntitiesAfterbirthPlus.xml''
What should I do? Should I create a file with that name in that directory? Sorry if this is a stupid request, I am very new to coding.
Thanks!
Update: It appears it is not recognising the file in the resources folder with that name. How do I fix this? Thanks again!

**Comment by Zamiell** [comment]
Don't open issues for basic technical support. Contact maintainers via Discord.
