### ISSUE TITLE
Not all rooms are visible?

### ISSUE THREAD

**Issue by bluddy** [Tempus/Basement-Renovator#2]
It seems like I can't view every room in the game. If you open the cellar stb and go to the last room, you'll get a blank window. Same for many of the later (bigger) rooms. 

1. Any idea why this is?
2. If I save after changing some rooms, will the undisplayed rooms be saved properly?

**Comment by Zamiell** [comment]
I'm not able to reproduce this in either the Rebirth or Afterbirth versions of Basement Renovator.
