### ISSUE TITLE
I'm having problems installing despite what my name says im not a pro programmer

### ISSUE THREAD

**Issue by ExtreamHackerManProProgrammer-imserious** [Tempus/Basement-Renovator#220]
"C:\Users\billy\Documents\Basement-Renovator-3.1.0>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

What should i do? I dont understand

**Comment by Zamiell** [comment]
does requirements.txt exist?

**Comment by ExtreamHackerManProProgrammer-imserious** [comment]
> does requirements.txt exist?

i thougt i was creating it with the command, so i just make that document with nothing in it then write the command?

**Comment by ExtreamHackerManProProgrammer-imserious** [comment]
yeah never mind its working now, exepct i cant change the theme of the room and half of the buttons in the rooms tab is unvisable.
