### ISSUE TITLE
Locked Out of My Floor's Rooms

### ISSUE THREAD

**Issue by guwahavel** [Tempus/Basement-Renovator#221]
I don't know what I did but now I can't access the rooms I made for the Cellar. Neither importing the STB or opening the XML file works. I already tried reinstalling Basement Renovator and deleting the mod's metadata file.

Error when I try to import STB
![error1](https://user-images.githubusercontent.com/78291137/106375497-25f1be00-6352-11eb-8804-0f07ea9afc75.png)

Error when I try to open XML
![error2](https://user-images.githubusercontent.com/78291137/106375495-22f6cd80-6352-11eb-9b1f-a3b0a529a478.png)

Log when opening Basement Renovator about Cellar
![launcherrorrr](https://user-images.githubusercontent.com/78291137/106375554-a4e6f680-6352-11eb-8fa4-9780b2ae55a4.png)

**Comment by budjmt** [comment]
Can you post the content in the XML file near line 9746? Sorry this is just getting noticed
