### ISSUE TITLE
No Boss Rooms

### ISSUE THREAD

**Issue by iii235** [Tempus/Basement-Renovator#239]
Hello, I'm new to Basement-Renovator and Isaac 
modding in general. I'm trying to modify boss rooms but the Renovator isn't finding any boss rooms for me to edit. I'm using the boss room flair, but nothing shows up becides a custom boss room I made. I'm playing on Repentance so I think it might be a compatibility error.
![Screenshot (57)](https://user-images.githubusercontent.com/62969347/118017916-28868b00-b325-11eb-99c7-21be3567e89a.png)

**Comment by Zamiell** [comment]
boss rooms are in the special rooms stb
