### ISSUE TITLE
Feature Request - "Test Room"

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#24]
There would be 2 different menu options:

1) "Test Room - Start Room" - This would copy the room to the "Start Room" in 00.special rooms.stb.
2) "Test Room - Basement" - This would make a 01.basement.stb and 02.cellar.stb with only 1 room in it, being the one you want to test.

**Comment by Zamiell** [comment]
Also, in the Basement mode, if the room being tested doesn't have doors on all sides, we will also need to add a blank 1x1 room with doors on all sides in order to prevent the game from crashing. When doing this, we should put the difficulty of the blank 1x1 room at 10, the difficulty of the test room at 1, and the weight of the test room at 1000.

**Comment by Tempus** [comment]
Okay, everything is implemented as specified above, with a few quality of life improvements added as well. Should be good to go! Untested on Windows.

**Comment by Zamiell** [comment]
When you try to test with no room selected, it crashes. It should instead handle this with a sane error message. Crash detail is below:

```
Traceback (most recent call last):
  File "BasementRenovatorAfterbirth.py", line 2331, in testStartMap
    self.storeEntityList(self.roomList.selectedRoom())
  File "BasementRenovatorAfterbirth.py", line 2016, in storeEntityList
    room.roomSpawns = spawns
AttributeError: 'NoneType' object has no attribute 'roomSpawns'
```

On Windows, doing a test with a normal room with an entity or two in it causes the following crash:

```
Traceback (most recent call last):
  File "BasementRenovatorAfterbirth.py", line 2298, in testMap
    resourcesPath = self.findResourcePath()
  File "BasementRenovatorAfterbirth.py", line 2399, in findResourcePath
    if not exePath:
NameError: name 'exePath' is not defined
```

**Comment by Tempus** [comment]
Pushed fixes, please verify.

**Comment by sillypears** [comment]
I just created a room and launched it via "Test Basement" and it worked fine. I had both the room I created (1 pedestal, 1 enemy, 1 pickup) as well as blank 1x1 rooms. I only tested with a 1x1 room as well.

**Comment by Zamiell** [comment]
If the room to be tested has doors on all sides, then there shouldn't be any blank 1x1 rooms inserted.

**Comment by Tempus** [comment]
This seems to be complete!
