### ISSUE TITLE
Random Item Pedestal is too high

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#25]
Small visual bug - it doesn't look like it does in-game, its sitting too high off where the entity actual exists.

**Comment by Tempus** [comment]
Yeah, this is because of the image anchoring to the bottom. Damn things need different anchor points. A lot of bosses are wrong too, as I'm sure you noticed while testing.

**Comment by Zamiell** [comment]
Closing since it is a duplicate of issue #23
