### ISSUE TITLE
Sheol Room 269 is bugged

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#28]
Entity 251.10.0 has no graphic.

**Comment by Zamiell** [comment]
I tested the room and they are weird eyeball enemies that immediately disappear? Not sure.

**Comment by Zamiell** [comment]
Also appears in Sheol room #255.

**Comment by Tempus** [comment]
These are Begotten Chains, they are attached to begotten and usually spawned by the game itself. Fixed.
