### ISSUE TITLE
Dark Room #292 is bugged

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#30]
Entity 5.70.11 has no graphic.

**Comment by sillypears** [comment]
Greed Boss room also is missing 406.1.0 (only 406.0.0 is avaiable) 

![image](https://cloud.githubusercontent.com/assets/13240985/12074941/44da3df0-b13d-11e5-99a1-c7f858a5aeb7.png)

**Comment by Tempus** [comment]
Fixed - it's just random pills.
