### ISSUE TITLE
Is there a way to change room type

### ISSUE THREAD

**Issue by sillypears** [Tempus/Basement-Renovator#32]
I only see an explicit way to edit variant and subvariant for a room. Is there a way to change it's type as well? It doesn't seem possible to create a new Boss room from what I've tried to do.

**Comment by Tempus** [comment]
You can only create boss rooms inside 00.special rooms.stb. For all other stbs, they are only valid with Null rooms or Normal rooms. The game will crash if the criteria isn't met, so my UI enforces it. To change type, right click and use the drop down menu.

**Comment by sillypears** [comment]
I was editing 25.ultra greed.stb and that doesn't follow this format.

**Comment by Tempus** [comment]
Hmm, good point. I'll have to address this in the future.

**Comment by Tempus** [comment]
Alright, I decided just to remove the restriction on room types. If people make alternate room types in basement.stb, it'll crash, but that's just how it is.
