### ISSUE TITLE
Duplicating Greed Boss & Other Things

### ISSUE THREAD

**Issue by sillypears** [Tempus/Basement-Renovator#34]
When duplicating the greed boss room it creates with the wrong shape (i think). I tried with another boss room on a greed file and the 13x7 room duplicated as a 7x7 room. Both have a weight 13. It seems that the parsing of the room on the duplicate button is off.

![image](https://cloud.githubusercontent.com/assets/13240985/12075380/79aaa97a-b14c-11e5-8421-3507da74af66.png)

![image](https://cloud.githubusercontent.com/assets/13240985/12075389/beb9d81a-b14c-11e5-8155-b09d2f2c9d38.png)

**Comment by Tempus** [comment]
Forgot to add the afterbirth data to duplicating. Fixed.
