### ISSUE TITLE
Show the pull path of the currently opened file in title bar

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#38]

**Comment by Tempus** [comment]
Used Qt's "setWindowFilePath" which may help the title bar issue. Needs verification on Windows.

**Comment by Zamiell** [comment]
Downloaded latest zip. Nothing appears to have changed as far as the title bar goes. =(

**Comment by Zamiell** [comment]
Maybe set window title manually by creating a string of path + filename?

http://stackoverflow.com/questions/27453436/set-application-name-in-pyside

**Comment by Tempus** [comment]
Closed because hate windows. And winter melons.
