### ISSUE TITLE
Implement Custom Entity Support (ala Jean-Alphonse's patches / zatherz's PR)

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#39]
See issue #3.

I don't personally care about this, but it would be nice to have it in Basement Renovator for the sake of completeness. Ask @zatherz for more info if you need to.

**Comment by Tempus** [comment]
I don't think I'll be implementing this, for a few reasons.

* The first is that I've had disagreements with zatherz in the past, and pulling his patches is likely to produce more drama than I'm interested in.
* The second is that his particular implementation isn't terribly good from an end-user experience perspective
* The third is that given the above, it's as simple or simpler for an experienced user to simply add their custom entities to the end of EntitiesAfterbirth.xml, which actually yields superior results UX wise.
* The last reason is that Afterbirth+ is scheduled for 'early 2016', so sometime in the next four months or so we are expecting modding support which is extremely likely to include custom enemies. I will likely need a new system to deal with the custom enemy output they decide to generate, so I don't feel like reinventing the wheel at this moment when I'll have to redo the work in the near future.

**Comment by zatherz** [comment]
Zamiell, I have told you that this suggestion will not work because of how much the patches are held by duct tape.

**Comment by Zamiell** [comment]
Gotcha.
