### ISSUE TITLE
Hovering Over Entity In Palette Shows Information

### ISSUE THREAD

**Issue by sillypears** [Tempus/Basement-Renovator#40]
Currently in WINDOWS 10 when hovering over an entity in the palette shows nothing. Would be very helpful to have this show the entity name, and potentially some other ID information.

**Comment by Zamiell** [comment]
Yeah, hovering doesn't do anything in Windows 7 either.

**Comment by Tempus** [comment]
I've set the tooltip, what's this, and status text already. Not sure how else to do this without making a custom classed tooltip. It would take a couple hours - how critical is this?

**Comment by sillypears** [comment]
Didn't realize it was actually in already. Wonder why it doesn't show up.

**Comment by Tempus** [comment]
Not sure, looking into it.

**Comment by sillypears** [comment]
Confirmed fixed :D

![image](https://cloud.githubusercontent.com/assets/13240985/12081443/202e15ca-b247-11e5-8acf-67ef227b03cb.png)
