### ISSUE TITLE
Needs a README.md file

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#41]
At the very least, there should be a brief description, version history, a link to the moddingofisaac subreddit, credits, and so forth. (Similar to: https://github.com/Zamiell/jud6s)

**Comment by Zamiell** [comment]
Or just include the stuff from: https://www.reddit.com/r/themoddingofisaac/comments/3ze00o/the_basement_renovator_a_new_contract_rc1/

**Comment by Zamiell** [comment]
Also, the binary links are broken (and also broken on Reddit).

**Comment by Tempus** [comment]
Updated to match github (???) conventions.

**Comment by Zamiell** [comment]
Links are still broken.
