### ISSUE TITLE
Py2exe no longer embeds application icons

### ISSUE THREAD

**Issue by Tempus** [Tempus/Basement-Renovator#43]
Py2exe no longer embeds application icons. It's supposed to be supported, but it errors when run. Gotta figure out a fix, or some way around it.

**Comment by Zamiell** [comment]
Recommend using cx_Freeze instead of py2exe.

**Comment by sillypears** [comment]
Yea, I believe Hyphenated also made the switch to cx_freeze and said it was better, as py2exe with python3 has minimal-to-nonexistant support.

**Comment by Tempus** [comment]
Alright, I'll look into it.

**Comment by Zamiell** [comment]
Does this apply to the Mac version or the windows version?

**Comment by Zamiell** [comment]
Closing in favor of #161.
