### ISSUE TITLE
Icon bug when opening a room with undefined room type

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#44]
![icon bug](https://cloud.githubusercontent.com/assets/245725/12092907/4269b3a6-b300-11e5-996c-3c74293419ac.png)

as you can see instead of displaying no icon, it displays all icons in the room header field. 
i used the standard 18.greed special.stb file and all 21 rooms on the bottom of the room list have this bug.

**Comment by Tempus** [comment]
Fixed. It's a whole new room type I overlooked, which I've called "Greed Mode Descent". I also added icons to the selector list.
