### ISSUE TITLE
Entity display improvements

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#45]
![unbenannt-1](https://cloud.githubusercontent.com/assets/245725/12093969/432170d0-b306-11e5-850e-44b49c64b65a.png)

Since the icons for lucky penny and cobweb are badly visible i improved them so they are more visible. here are the new icons:
![1940 0 0 - cobweb](https://cloud.githubusercontent.com/assets/245725/12094036/9f62ac92-b306-11e5-931c-c3ae39ae96bc.png)
![5 20 5 - lucky penny](https://cloud.githubusercontent.com/assets/245725/12094039/a3096d68-b306-11e5-9883-9a5d40f2fd72.png)

In addition to that it would be nice to change the display order of some pickups to make the order more consistent and more visible. So you can put the batterie as the last entry, switch the golden key and double key, maybe add a spacer between keys and bombs, and put the random rune in the front of the row like it is in all other rows.

**Comment by sillypears** [comment]
I already provided icons for this, but as @Tempus is a designer himself he created his own. See issue #13. The Cobweb does make sense. 

I believe the order is just how they are pulled in from the entity xml file, but this could be tested by reordering the files in there. Seems like a simple fix if that's the case. 

Casting the bombs to one side seems like a minimal improvement, with a lot of work on the code side to do it.

**Comment by wofsauge** [comment]
i tried editing the entitiesAfterbirth.xml but this somehow does have no effect on the order.
The spacer is just an idea. if it is to much work the devs can leave this out.

**Comment by sillypears** [comment]
Might have to do with the type.variant.subtype ID as well. Hearts have the same type.variant, where a battery is a totally different type of variant.

**Comment by Tempus** [comment]
Fixed. No spacer was made, split up keys and bombs into their own categories.
