### ISSUE TITLE
Issue with Entities at Negative X/Y Positions

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#46]
See this:

http://www.twitch.tv/ou_j/v/33498219

I didn't even modify this room in Jud6s.

Edit - [snip] See below comment.

**Comment by Tempus** [comment]
If you can provide a screencap of your level to go with this issue, that would be swell.

**Comment by Zamiell** [comment]
Ok, so its an issue specifically with Depths room #463. (The room isn't in Necropolis.) Here's what the room looks like in XML:

```
  <room type="1" variant="463" subtype="0" name="New Room" difficulty="10" weight="1" width="13" height="7" shape="1">
    <door x="13" y="3" exists="True" />
    <door x="6" y="-1" />
    <door x="6" y="7" />
    <door x="-1" y="3" exists="True" />
    <spawn x="4" y="-1">
      <entity type="241" variant="0" subtype="0" weight="1" />
    </spawn>
    <spawn x="8" y="-1">
      <entity type="241" variant="0" subtype="0" weight="1" />
    </spawn>
```

There are pits all along the top of the room, so the spiders can't be placed along the top. So instead they are placed out of bounds at -1 Y. And then, when the room is loaded, they snap back in bounds to where they are supposed to be.

This fucks up Basement Renovator because it appears to be hardcoded to not allow entities at negative X and Y placements. Furthermore, BR doesn't even SHOW the wall creeps upon loading the room.

So maybe two fixes:

1) Allow entities to be placed at X/Y -1 (but not -2 or higher).
2) Show entities placed at X/Y -1 (but not -2 or higher).

**Comment by sillypears** [comment]
I am writing a quick script to go through all STBs that @Zamiell edited to look for this and will provide room ID for it.

**Comment by Zamiell** [comment]
```
04.caves_converted.xml
ID:1.203.0 x:6 y:-1
ID:1.363.0 x:6 y:-1
ID:1.363.0 x:19 y:-1
ID:1.406.0 x:6 y:-1
ID:1.406.0 x:19 y:-1
ID:1.427.0 x:6 y:-1
ID:1.427.0 x:19 y:-1
ID:1.429.0 x:6 y:-1
ID:1.429.0 x:19 y:-1

05.catacombs_converted.xml
ID:1.363.0 x:6 y:-1
ID:1.363.0 x:19 y:-1
ID:1.406.0 x:6 y:-1
ID:1.406.0 x:19 y:-1
ID:1.427.0 x:6 y:-1
ID:1.427.0 x:19 y:-1
ID:1.429.0 x:6 y:-1
ID:1.429.0 x:19 y:-1

07.depths_converted.xml
ID:1.430.0 x:-1 y:-1
ID:1.455.0 x:5 y:-1
ID:1.455.0 x:11 y:-1
ID:1.463.0 x:4 y:-1
ID:1.463.0 x:8 y:-1

08.necropolis_converted.xml
ID:1.430.0 x:-1 y:-1
ID:1.455.0 x:5 y:-1
ID:1.455.0 x:11 y:-1
```

This is from Sillypear's script. Putting it here for now. I'll edit this later probably and clean it up.

**Comment by Zamiell** [comment]
You worked on this for a while back, did you find a good way to handle this?

**Comment by Zamiell** [comment]
Just for documentation purposes, there appears to be no new OOB (out of bounds) entities in the new Afterbirth+ rooms.

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/180

**Comment by Zamiell** [comment]
tested with Depths room 463 and it seems to be fixed, praise budjmt
