### ISSUE TITLE
Searching by entity is broken in the latest build

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#47]
For example, there are 2 "The Haunt" rooms on the chest, but none appear in the list when searching for the Haunt entity.

**Comment by Zamiell** [comment]
Looks like it broke somewhere between commit e5256de63fb631f526d20593be1c27c5407a7655 and commit 1968b340953ee14e537b45400165cf1de6634e5d.

**Comment by Tempus** [comment]
Fixed.
