### ISSUE TITLE
It is possible to use rooms other than 1x1 as the Start Room

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#51]
"You may only test 1x1 rooms as the Start Room"

This isn't strictly true, according to my testing today. All sizes should be possible to use except for size #9, which is the L shape without a top-left part.

**Comment by Tempus** [comment]
In addition, the narrow 0.5 tall by 1 wide room will also be glitched, as it spawns you outside the room. In addition, the doors are gltiched, but I suppose that won't matter for start room testing.

**Comment by Tempus** [comment]
Fixed! All sizes but 2 and 9 now valid.
