### ISSUE TITLE
If you open a vanilla darkroom.stb, it doesn't show all of the rooms

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#52]
It only shows a  tiny subset of all of the rooms. Is this happening with all of the floor STBs? Not sure.

**Comment by wofsauge** [comment]
what rooms are not working ? i tested this bug with a normal 18.dark room.stb from the afterbirth files and it displays all rooms and all are selectable...

**Comment by Zamiell** [comment]
Never mind, not able to reproduce this bug now for some reason. Maybe I had some filter on and didnt notice it?
