### ISSUE TITLE
Testing Mode Major Bugs

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#53]
Warning to everyone else, be wary of testing mode!

1) When making the Jud6s mod, at some point over the past 2 days testing mode completely replaced my special rooms STB with the slimmed down version. I had to start over from scratch using a vanilla special rooms STB and now I'm too afraid to use testing mode at all. I suspect that this happens when doing a "start room test" inside of a special rooms STB.

2) When testing certain rooms in "basement test", it changes the weight of the room to 1000. However, it actually appears to be doing this to the actual STB, as when I shipped the Jud6s mod, several rooms stayed as weight 1000 and I had to go through every room in the game as reapply weight 1.

**Comment by Tempus** [comment]
Was your special rooms.stb perhaps in the isaac rooms folder to begin with?

**Comment by Zamiell** [comment]
Not 100% sure, perhaps at some time yes when doing testing I was copying it back and forth between the Isaac directory and my GitHub repo directory.

**Comment by Zamiell** [comment]
I started to make the mod again today from scratch and I used test mode on a completely separate STB, but somehow after finishing and loading my original it overwrote the one I was working on with the minified one. Not sure how this is happening but its pretty devastating.

**Comment by Tempus** [comment]
Not sure why this happened, but added a dirt check to testing, so that you will never be able to quit without prompting if your file has been clobbered. Also added a message to recommend extra saving and warn of issue when it's likely to occur.

**Comment by Tempus** [comment]
Also room weight reseting fixed.
