### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by Tweevle** [Tempus/Basement-Renovator#54]
Some entities that were added in Afterbirth aren't in the editor, usually ones that aren't in rooms in normal play but it'd be good to have the option as we already have things like tears. Here's a list of ones I could find and what category I suggest putting them in:

251.10.0 [Begotten Chain] - Stage/Broken (this one is actual in some rooms already, and crashes the editor when you click on it)

291.0.0 [Pitfall] - Stage/Traps
291.3.0 [Teleport Pitfall] - Stage/Traps

293.0.0 [Ultra Greed Coin (Spinner)] - Stage/Tears
293.1.0 [Ultra Greed Coin (Key)] - Stage/Tears
293.2.0 [Ultra Greed Coin (Bomb)] - Stage/Tears
293.3.0 [Ultra Greed Coin (Heart)] - Stage/Tears

294.0.0 [Ultra Greed Door] - Stage/Broken

295.0.0 [Corn Mine] - Stage/Traps

296.0.0 [Hush Fly] - Enemies/Flies

297.0.0 [Blue Boil] - Enemies/Boils

298.0.0 [Greed Gaper] - Enemies/Gapers

**Comment by Tempus** [comment]
Fixed. 291.2.0 was teleport pitfall, 291.3.0 was blue hush pitfall. 297.0.0 was blue gaper. 298 was blue boil. 299.0.0 was Greed gaper.
