### ISSUE TITLE
Feature Request: Pinning filter-by-entity

### ISSUE THREAD

**Issue by Tweevle** [Tempus/Basement-Renovator#57]
Currently, you can filter rooms by entities by selecting them in the palette, and when you select a different entity in the palette it changes the filter. This can be a problem if you want to keep that filter, for example if you want to go through all rooms that contain a particular entity and replace it with others, you have to keep reselecting the previous entity. I suggest adding an option to "pin" the filter in place, e.g. by holding ctrl when you click the button. This will keep the currently selected entity as the filter and not change until you ctrl-click it again.

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/164 happy to finally get this in!

**Comment by Zamiell** [comment]
booyah
