### ISSUE TITLE
Make a way to display room ID on the right column instead of room name

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#6]
Otherwise it is difficult to find the exact room you are looking for.

OR maybe add room ID as a prefix to the name. Like "313 - Pin" or whatever.

**Comment by Tempus** [comment]
Will probably make a multi-column list for names to allow for easier editing. Will work on it.

**Comment by Tempus** [comment]
Unfortunately, multi-column requires a rewrite of many things, annoyingly. Implemented a basic thing for now, gonna improve it a little more but =|

**Comment by Zamiell** [comment]
Its perfect!

**Comment by Tempus** [comment]
Fixed. Gonna add an ID filter as well, maybe a toggle.
