### ISSUE TITLE
Graphic for Troll Bomb and Mega Troll Bomb are the same

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#64]
This is specifically regarding the section "Live Bombs". They are both the graphic for Mega Troll Bomb.

**Comment by JCapparelli** [comment]
![4 0 3 - troll bomb](https://cloud.githubusercontent.com/assets/16618069/12217065/9fade9cc-b6c2-11e5-88de-bdb1ef93ebab.png)

Here's the graphic. Put it in resources/Entities and rename it 4.0.3 - Troll Bomb.png

**Comment by Tempus** [comment]
Fixed.
