### ISSUE TITLE
Upon opening an STB file it crashes

### ISSUE THREAD

**Issue by BeenBean** [Tempus/Basement-Renovator#72]
Whenever I open an STB file the program crashes. I tried running it from the program directory and it still did not work. I cant even find the crash log and am unsure if there is one.

**Comment by JCapparelli** [comment]
You might be opening the wrong stbs. For example, is your chest stb 12 or 17? If it's 12, you have the wrong file. Afterbirth's rooms are in afterbirth.a and not rooms.a

**Comment by Tempus** [comment]
This is certinaly another Afterbirth/Rebirth issue. I'll reopen that as a feature I need to add.
