### ISSUE TITLE
Add Rebirth support

### ISSUE THREAD

**Issue by Tempus** [Tempus/Basement-Renovator#73]
Really, there's no reason I can't backport.

**Comment by Zamiell** [comment]
This would be possible by just reading the bytes of the header of the STB to know if its a Rebirth STB or an Afterbirth STB?

**Comment by Zamiell** [comment]
Partial Rebirth support is in. It still shows all the afterbirth ents and doesn't account for adjusted entity ids.

**Comment by Zamiell** [comment]
Will close for now.
