### ISSUE TITLE
Sprite Corrections/Improvements

### ISSUE THREAD

**Issue by JCapparelli** [Tempus/Basement-Renovator#74]
-The sprite for the Gurgle enemy is a headless plain body instead of the green zombie sprite: ![87 0 0 - gurgle](https://cloud.githubusercontent.com/assets/16618069/12443245/a05a1052-bf24-11e5-82ab-48edf809bb92.png)
-The teleport pitfall uses the wrong sprite due to xml error
- Current: Image="resources/Entities/291.0.0 - Pitfall.png"
- Correct: Image="resources/Entities/291.2.0 - Teleport Pitfall.png"

-Here's some other sprite improvements to better familiarize enemies:
![91 0 0 - swarmer](https://cloud.githubusercontent.com/assets/16618069/12443335/299056f6-bf25-11e5-8ba3-29512304e27b.png) ![257 001_blueconjoinedfatty](https://cloud.githubusercontent.com/assets/16618069/12443338/2d035f68-bf25-11e5-9c6d-8bcac6b64815.png) ![74 0 0 - blastocyst big](https://cloud.githubusercontent.com/assets/16618069/12443339/32aceb3c-bf25-11e5-83cd-724be043fbc6.png) ![74 0 0 - blastocyst medium](https://cloud.githubusercontent.com/assets/16618069/12443346/3ba40964-bf25-11e5-880d-e3f2d0dcd495.png) ![74 0 0 - blastocyst small](https://cloud.githubusercontent.com/assets/16618069/12443361/5d54e628-bf25-11e5-987f-a61fefb51f1b.png) ![283 0 0 - bone knight](https://cloud.githubusercontent.com/assets/16618069/12443367/66a6e64a-bf25-11e5-857e-bb75b8cfb92f.png)
![284 0 0 - cyclopia](https://cloud.githubusercontent.com/assets/16618069/12443365/628164dc-bf25-11e5-97d9-82db56427f2f.png) ![39 3 0 - scarred double vis](https://cloud.githubusercontent.com/assets/16618069/12443370/6caa9ff0-bf25-11e5-9a28-7abc99d75a99.png) ![49 0 0 - gluttony](https://cloud.githubusercontent.com/assets/16618069/12443377/741e725c-bf25-11e5-9dd0-148b059d9776.png) ![49 1 0 - super gluttony](https://cloud.githubusercontent.com/assets/16618069/12443382/77d2de56-bf25-11e5-9784-98bc3d60eee2.png)
- *Is Cyclopia a gapper or a maw? ._.*

-Here is a zip file containing the sprites with the proper name format: http://www.filedropper.com/sprites

**Comment by Tempus** [comment]
All updated and fixed! Thanks for the images and sorry for the slow response.
