### ISSUE TITLE
Collectible "<3" is missing

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#77]
Image is missing and entry is wrong:

`	<entity Group="Passive Items" ID="5" Image="resources/Entities/Items/5.100.15 - &lt;3.png" Kind="Collect" Name="&lt;3" Subtype="15" Variant="100" />`

should be 

`	<entity Group="Passive Items" ID="5" Image="resources/Entities/Items/5.100.15 - 3.png" Kind="Collect" Name="&lt;3" Subtype="15" Variant="100" />`

**Comment by Tempus** [comment]
Fixed.
