### ISSUE TITLE
Collectible "Bob`s Curse" is missing

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#78]
Entry of bobs curse:
`<entity Group="Passive Items" ID="5" Image="resources/Entities/Items/5.100.140 - Bob's Curse.png" Kind="Collect" Name="Bob's Curse" Subtype="140" Variant="100" />`

should be

`<entity Group="Passive Items" ID="5" Image="resources/Entities/Items/5.100.140 - Bobs Curse.png" Kind="Collect" Name="Bob's Curse" Subtype="140" Variant="100" />`

**Comment by Tempus** [comment]
Fixed.
