### ISSUE TITLE
Collectible "20/20" is missing

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#79]
Entry:

`<entity Group="Passive Items" ID="5" Image="resources/Entities/Items/5.100.245 - 20/20.png" Kind="Collect" Name="20/20" Subtype="245" Variant="100" />`

should be changed to:

`<entity Group="Passive Items" ID="5" Image="resources/Entities/Items/5.100.245 - 20-20.png" Kind="Collect" Name="20/20" Subtype="245" Variant="100" />`

**Comment by Tempus** [comment]
Fixed.
