### ISSUE TITLE
Remove the "white doors" graphic

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#8]
This is just a cosmetic / quality of life change.

When a door is disabled for a room, Basement Renovator turns it white, which is kind of dumb. It would look a lot better if the door was just removed entirely, similar to how a real room would look in-game.

**Comment by Tempus** [comment]
Unfortunately, this is done for a UI reason. If the door disappears, users have no visual feedback as to how they might reactivate the door, or where the door might be to click on it and reactivate it. I can replace it with some other graphic if you think it would be better, but it definitely needs a visual indicator.

**Comment by Zamiell** [comment]
Hrm, ok. Maybe just a faded door would look better? I didn't know about the double clicking thing to toggle door spawns.

**Comment by Tempus** [comment]
I've decided to close this issue - it's just not super important and I can't think of a good way to resolve it.
