### ISSUE TITLE
Trinket "NO!" is missing

### ISSUE THREAD

**Issue by wofsauge** [Tempus/Basement-Renovator#80]
Code:

`<entity Group="Trinkets" ID="5" Image="resources/Entities/Trinkets/5.350.088 - NO!.png" Kind="Collect" Name="NO!" Subtype="88" Variant="350" />`

should be changed to:

`<entity Group="Trinkets" ID="5" Image="resources/Entities/Trinkets/5.350.088 - NO.png" Kind="Collect" Name="NO!" Subtype="88" Variant="350" />`

**Comment by Tempus** [comment]
Fixed.
