### ISSUE TITLE
needs more checking before doing file operations

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#81]
BR will crash if it tries to move/remove a file that doesn't exist.
Happens fairly often when using the test room features. =(

**Comment by Tempus** [comment]
Can you give me an exact error after pulling from head? From what I can see, all test room lines have a file exist check.

**Comment by Zamiell** [comment]
You can reproduce the crash if you delete the rooms directory and then click the "ok" button.

**Comment by Tempus** [comment]
Seems alright now.
