### ISSUE TITLE
Feature: Reset Windows to Defaults

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#85]
After moving the toolbars around, it is a little unintuitive on how to get them back to defaults. On Windows, the little highlight thing doesn't even always show when dragging a panel towards the side, which seems buggy. Furthermore, when you close the program and reopen, it will remember all of the window placements, so there's no way to get it back to "normal".

Just make a new entry under the "View" menu called "Reset All Panels to Defaults".

**Comment by Tempus** [comment]
Done. Reset Window Deafults added to the view menu. Also fixed window geo saving.
