### ISSUE TITLE
no support for 32 bit?

### ISSUE THREAD

**Issue by jpog7** [Tempus/Basement-Renovator#88]
recently tried to install the basement renovator for windows and i thought the .exe was broken. however it said that it couldn't specify the system bit type. i have used the old rebirth renovator  before and it worked flawlessly so im wondering why it wont work now especially after reading the comments that the said the new renovator was built from the old one.

**Comment by Tempus** [comment]
Are you running 32 or 64 bit windows? And could you post the exact error text?

**Comment by MeIsZ** [comment]
I'm having the same issue, Your tool used to work on my system, and now it does not.
I'm using a 32bit system, my os is Windows 7 Home Premium.
This is the error:
![screen shot 2016-05-22 at 8 21 07 pm](https://cloud.githubusercontent.com/assets/19523567/15458706/c845fb98-205a-11e6-86bc-4c8ebace0732.png)

**Comment by Zamiell** [comment]
@Tempus This issue will probably go away if you use the latest version of cx_freeze of pyinstaller instead of py2exe.

**Comment by jpog7** [comment]
Will try, hopefully it works.

BTW the old version of basement renovator(For rebirth) works fine on my pc even with no python and all that other stuff.

**Comment by Zamiell** [comment]
This issue should be fixed in the next release of Basement Renovator (the one that will introduce Afterbirth+ compatibility).

Please make a new issue if it is still broken at that time.
