### ISSUE TITLE
Selecting wrong item instead of 'resources' causes unrecoverable crashes

### ISSUE THREAD

**Issue by Tempus** [Tempus/Basement-Renovator#92]
When you mis-select the 'resources' folder during a test, the wrong selection causes crashes on launch.

**Comment by budjmt** [comment]
As of https://github.com/Tempus/Basement-Renovator/pull/133, this should no longer be the case. Currently it's just a silent failure, I'll add a pop up alerting that the resources/mod path is invalid.

**Comment by budjmt** [comment]
fixed in https://github.com/Tempus/Basement-Renovator/pull/150

**Comment by Zamiell** [comment]
woot
