### ISSUE TITLE
Won't recognize pyqt5 in terminal

### ISSUE THREAD

**Issue by BeezWaxandnectar** [Tempus/Basement-Renovator#95]
Hi. I'm using a mac, and after following the instructions you have given, The terminal responded with: ImportError: No module named 'PyQt5'
I have installed PyQt5, so, I don't know what the problem is.

**Comment by Zamiell** [comment]
The GitHub issues page is meant for reporting issues with this specific repository; it is not meant as technical support to teach you how to run Python programs. Sorry!
