### ISSUE TITLE
Windows Compatibility Problem:

### ISSUE THREAD

**Issue by luigimario8888** [Tempus/Basement-Renovator#96]
I own a Windows 32 computer, and when I try to run the Basement Renovator for The Binding of Isaac Afterbirth, it gives me this message:

![goddamit 69](https://cloud.githubusercontent.com/assets/24992218/21752447/a0cddab0-d59d-11e6-8d2c-969f799fee9a.png)

I heard that the previous versions of the Basement Renovator are compatible with Windows 32, so I was wondering if there was anything I could do to make this work for me.

**Comment by Zamiell** [comment]
This issue should be fixed in the next release of Basement Renovator (the one that will introduce Afterbirth+ compatibility).
